### ISSUE TITLE
Freeze on formatting disk in TS-DOS 

### ISSUE THREAD

**Issue by explit28** [bkw777/TPDD_Cable#1]
Hello Brian and thank you very much for your great projects! I purchased all parts needed and soldered the cable.
When i connect my Brother FB100 Floppy drive to my NEC PC-8201 and try to read the Floppy with TS-DOS -
the disk is being accessed. Access LED light up, drive reads the floppy and TS-DOS tells me that the disk is not formatted.
It shows me the message:
`Insert Floppy and press "Y" to format`
If i press the Y-Key - the computer freezes and i need to reset it to be able to read again.

Is there any other way to test the floppy on the NEC PC-8201?

Thank you very much

**Comment by bkw777** [comment]
There's a few things to check / know

If you didn't replace the belt in the drive, it definitely needs a new belt. The original belts are all turned to goo by now. So google up a FRW-8.5 belt and discard any that cost more than $10.

The freeze is not really a freeze, it would probably time out on it's own after about 2 minutes. I don't remember specifically if TS-DOS has such a time out, I just say that because at the protocol level, the format command doesn't return any kind of ongoing progress nor is there a way to poll for progress except at the end when it's all done, and that takes over 100 seconds on a normal working drive. The whole time the drive is busy formatting, there is nothing passing over the wire, and if the client even tried to send anything it would just cause an error since the drive firmware isn't expecting it. So once ts-dos issues the format command, it's expecting to just sit there for about 100 - 110 seconds, not receiving anything and not allowed to send anything.

So if the drive has a bad belt, the client can still communicate with the drive, you could issue commands that make the motor run, and all disks would look like unformatted to the drive firmware, and a format command would probably just cause the drive to spin for 100 seconds, or maybe less before the drive could even tell that it did't work. The format command does do it's own verify but I don't know if it does that for each track along the way or only at the end after doing all tracks. So the drive might possibly know that the disk isn't working right away or maybe not until a minute later. Even if it does try to veryify after the first track and detect the failure right away, TS-DOS might be waiting 100 seconds before even looking (unlikely but possible).

When you wired up the cable, did you verify with a continuity tester that you got the right DB25 pin numbers connected to the matching numbers on the pcb? I included the color codes for the cables I used but you really can't trust the colors.

Also you got the polarity right, the extra 2 female header positions to make the polarity bump are on the opposite side from the  transistors? Transistors down, polarity bump up.

The symptoms are all consistent with needing a belt so maybe it's just that. Unfortunately the fb-100 / tpdd1 are a little bit more finnicky to do the belt than the tpdd2, but not too bad.

**Comment by bkw777** [comment]
You can test iwth pdd.sh from linux or mac. You'll need a usb-serial adapter and a particular 9-25 adapter or a combination of adapters. I have links and info all in a hardware document on the pdd.sh readme.
github.com/bkw777/pdd.sh
It is exactly a swiss army knife for operating and debugging a drive. Unfortunately it doesn't have great docs. Start with the readme and then look at all the cases in the big case statement in do_cmd(), and follow each of those to whatever function it calls to figure out the parameters for things not in the readme.

But the easy thing is just if you issue a condition or status command, and geat a meaningful respoonse at all, then you have cleared the cable. Connect the drive, turn the drive on, then start pdd.sh in tpdd1 mode, and 9600 speed because fb-100 only runs at 9600, and issue a "cond" command.

```
bkw@fw:~$ BAUD=9600 DEBUG=2 pdd1
1) /dev/ttyUSB0
2) /dev/ttyUSB1
Which serial port is the TPDD drive on? 2
Using port "/dev/ttyUSB1"
speed 9600 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W;
lnext = ^V; discard = ^O; min = 1; time = 1;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff -iuclc -ixany -imaxbel -iutf8
-opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig -icanon iexten -echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
PDD(opr:6.2,F)> cond
_init()
fonzie_smack()
ocmd_send_req: fmt="08" len="00" dat="" chk="F7"
tpdd_read: l=8 30 30 45 30 30 30 30 30
fcmd_read_ret: 00E00000
fcmd_read_ret: err:0="OK" res:224 len:0
Disk Write-Protected
Disk Changed
Disk Not Inserted
PDD(fdc:6.2,F)> 
```
 
The tpdd_read: there shows the data read from the drive, and the rest parsed it, and the last few lines shows that it was a meaningful response not garbage. this was on a Purple Computing (same as fb-100 or tpdd1) 

I only got prompted for the serial port because I had more than one usb serial adapter plugged in at the time.
 
Normally you don't bother manually using pdd1 vs pdd2 commands, just say "pdd commands..." and it automatically determines which kind of drive it is on startup. But in this case I just said the more explicit command to remove variables.

It doesn't automatically determine baud rate though. The default is 19200 because both tpdd1 and tpdd2 run at 19200, but fb-100 is hardwired to 9600. There is a little door on the bottom and it will run at 19200 if you flip all the dip switches to off. But on fb-100 I think usually there is no dip switch installed and there is just a solder blob bridging one of the positions. You could clear that solder blob and the drive will run at 19200 if you wanted. My purple computing has switches installed but I don't know if that was original or just the purple computing did that to theirs or some owner did it along the way. Then again... I don't think it makes actual operation much faster. Most of the time is spent waiting for the drive hardware to actually read/write the disk, and each side always waiting for the other side to process and ack each 128 byte command/packet before proceeding to the next.

**Comment by bkw777** [comment]
Better yet, DEBUG=3, and this time with only one usb adapter plugged in, and letting it automatically figure out the drive model,
and using the status command instead of the condition command. They both report drive status, but "cond" is an FDC-mode command and ends up switching the drive from opr to fdc mode which just adds another complicating detail so let's use status instead.

If you try this and get a drive status like at the bottom of this, then you have verified the cable and serial connnection and communication both directions. If not, then paste whatever you get here and maybe I can say where it went wrong.
This is a rebadged FB-100 with no disk inserted. Your drive even with a bad belt should produce identical output to this.

```
bkw@fw:~$ BAUD=9600 DEBUG=3 pdd
get_tpdd_port()
Using port "/dev/ttyUSB0"
open_com()
set_stty()
speed 9600 baud; rows 0; columns 0; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>; start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W;
lnext = ^V; discard = ^O; min = 1; time = 1;
-parenb -parodd -cmspar cs8 hupcl -cstopb cread clocal crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff -iuclc -ixany -imaxbel -iutf8
-opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig -icanon iexten -echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc
PDD(opr:6.2,F)> status
do_cmd(status)
_init()
fonzie_smack()
tpdd_drain()
tpdd_check()
tpdd_write(4D 31 0D)
tpdd_drain()
tpdd_check()
tpdd_write(5A 5A 08 00 F7)
tpdd_drain()
tpdd_check()
tpdd_write(4D 31 0D)
tpdd_drain()
tpdd_check()
ocmd_pdd2_unk23()
ocmd_send_req(23)
calc_cksum(23 00):DC
ocmd_send_req: fmt="23" len="00" dat="" chk="DC"
tpdd_write(5A 5A 23 00 DC)
ocmd_read_ret()
ocmd_read_ret: reading 2 bytes (fmt len)
tpdd_read(2)
tpdd_wait()
tpdd_check()
tpdd_check()
Detected TPDD1
ocmd_ready()
ocmd_send_req(07)
calc_cksum(07 00):F8
ocmd_send_req: fmt="07" len="00" dat="" chk="F8"
tpdd_write(5A 5A 07 00 F8)
ocmd_read_ret(5000)
ocmd_read_ret: reading 2 bytes (fmt len)
tpdd_read(2 5000)
tpdd_wait(5000)
tpdd_check()
tpdd_check()
tpdd_read: l=2 tpdd_wait()
tpdd_check()
tpdd_wait()
tpdd_check()
12 01
ocmd_read_ret: reading 1 bytes (data)
tpdd_read(1)
tpdd_wait()
tpdd_check()
tpdd_read: l=1 tpdd_wait()
tpdd_check()
71
ocmd_read_ret: reading 1 byte (checksum)
tpdd_read(1)
tpdd_wait()
tpdd_check()
tpdd_read: l=1 tpdd_wait()
tpdd_check()
7B
ocmd_read_ret: fmt=12 len=01 dat=(71) chk=7B
verify_checksum(12 01 71 7B)
calc_cksum(12 01 71):7B
verify_checksum: given:7B calc:7B
ocmd_check_err()
ocmd_check_err: ret_fmt=12 ret_len=01 ret_dat=(71) read_err="0"
ocmd_check_err: 71:Disk Not Inserted or Disk Change Error
Not Ready

status: Disk Not Inserted or Disk Change Error
PDD(opr:6.2,F)> q
do_cmd(q)
fcmd_mode(1)
bkw@fw:~$ 
```

**Comment by bkw777** [comment]
https://github.com/bkw777/pdd.sh/blob/main/hardware.md

**Comment by bkw777** [comment]
Actually... I'm dumb, if you got a message from TS-DOS saying disk not formatted, I think that already proves the communication is good, so you can skip pdd.sh and just open the case to check the belt and I bet it'll be bad.

**Comment by explit28** [comment]
Hello Brian!
   Thank you for taking so much time for my problem and your very good explanations.
   i will go for a new belt and will let you know!
   thank you very much!
  
  
   Pawel
  
  
  
   On October 18, 2022 at 6:09 AM Brian K. White ***@***.***> wrote:
   
     
    Actually... I'm dumb, if you got a message from TS-DOS saying disk not formatted, I think that already proves the communication is good, so you can skip pdd.sh and just open the case to check the belt and I bet it'll be bad.

**Comment by bkw777** [comment]
What ever happened?

**Comment by explit28** [comment]
I got a new belt and anything was fine! Thanks again!
